Adapt the Transifex synchronization processes to their new API (v3)

diff --git a/po/Makefile.am b/po/Makefile.am
--- a/po/Makefile.am
+++ b/po/Makefile.am
@@ -102,9 +102,14 @@ $(UPDATEGMODIRS):
 # too much
 
 TXTARGETS = tx-update tx-pull tx-push
+
+TX        = tx
+TXORG     = artic-games
 TXPROJ    = freedroid-rpg
-TXPROPS   = '{"category":"autoTM"}'
-TXCRED    = $(shell $(top_srcdir)/po/tx-credentials)
+TXPROPS   = '{"category":["autoTM"]}'
+TXCRED    = $(shell $(top_srcdir)/po/tx-credentials -t)
+TXHOST    = $(shell $(top_srcdir)/po/tx-credentials -r)
+
 # Create a list of potfiles:
 #  foreach dir in $SUBDIRS - $(foreach ...)
 #    - extract from Makevars the value of the DOMAIN parameter - $(shell ...)
@@ -127,17 +132,26 @@ $(TXTARGETS):
 	     $(mkdir_p) tx; \
 	     msgcat --width=80 --no-wrap --sort-by-file --use-first -o tx/all_in_one.pot $(TXPOTS); \
 	     if test -r tx/all_in_one.pot; then \
-	       if ! tx -q status -r $(TXPROJ).all_in_one >/dev/null 2>/dev/null; then \
+	       if ! $(TX) status $(TXPROJ).all_in_one >/dev/null 2>/dev/null; then \
 	         echo "Creating all_in_one"; \
-	         tx -q config mapping -r $(TXPROJ).all_in_one --source-lang en --type PO --source-file tx/all_in_one.pot --expression "tx/all_in_one-<lang>.po" --execute; \
-	         if tx -q push -r $(TXPROJ).all_in_one -s; then \
-	           curl_output=`curl -s -L $(TXCRED) -X PUT -d $(TXPROPS) -H "Content-Type: application/json" https://www.transifex.com/api/2/project/$(TXPROJ)/resource/all_in_one;` \
+	         $(TX) add --file-filter="tx/all_in_one-<lang>.po" --type=PO --organization=$(TXORG) --project=$(TXPROJ) --resource="all_in_one" tx/all_in_one.pot; \
+	         if $(TX) push -s $(TXPROJ).all_in_one; then \
+	           curl_output=`curl --request PATCH \
+	                        -s -o /dev/null -w "%{http_code}" \
+	                        --url $(TXHOST)/resources/o%3A$(TXORG)%3Ap%3A$(TXPROJ)%3Ar%3Aall_in_one \
+	                        --header 'Accept: application/vnd.api+json' \
+	                        --header 'Authorization: Bearer $(TXCRED)' \
+	                        --header 'Content-Type: application/vnd.api+json' \
+	                        --data '{ "data": { "attributes": $(TXPROPS), \
+	                                            "id": "o:$(TXORG):p:$(TXPREFIX):r:all_in_one", \
+	                                            "type": "resources" } \
+	                                }'`; \	           
 	           rtn=$$?; \
-	           if test $$rtn -ne 0 -o " $$curl_output" != " OK"; then echo "Warning. Failed to set properties: $$curl_output (error code $$rtn)"; fi; \
+	           if test $$rtn -ne 0 -o " $$curl_output" != " 200"; then echo "Warning. Failed to set properties: error code $$culr_output"; fi; \
 	         fi; \
 	       else \
 	         echo "Updating all_in_one"; \
-	         tx -q push -r $(TXPROJ).all_in_one -s; \
+	         $(TX) push -s $(TXPROJ).all_in_one; \
 	       fi; \
 	     fi; \
 	     rm -rf tx; \
diff --git a/po/l10n-others/Makefile.am b/po/l10n-others/Makefile.am
--- a/po/l10n-others/Makefile.am
+++ b/po/l10n-others/Makefile.am
@@ -26,29 +26,47 @@ l10n-clean:
 
 #== Transifex synchronization - Shared functions definition
 
+CURL     = curl
 TX       = tx
+TXORG    = artic-games
 TXPROJ   = freedroid-rpg
-TXPROPS  = '{"category":"other"}'
-TXCREDS  = $(shell $(top_srcdir)/po/tx-credentials)
+TXPREFIX = other
+TXPROPS  = '{"category":["other"]}'
+TXCRED   = $(shell $(top_srcdir)/po/tx-credentials -t)
+TXHOST   = $(shell $(top_srcdir)/po/tx-credentials -r)
 
 LANGS = $(shell tail -n +2 $(srcdir)/LINGUAS)
+comma:= ,
+empty:=
+space:= $(empty) $(empty)
+TXLANGS = $(subst $(space),$(comma),$(LANGS))
+
 
 #-- Update tx rsrc
 # $(1) = rsrc name
 # $(2) = rsrc file
 
 define rsrc_update =
-	if ! $(TX) -q status -r $(TXPROJ).$(1) >/dev/null 2>/dev/null; then \
+	if ! $(TX) status $(TXPROJ).$(1) >/dev/null 2>/dev/null; then \
 	  echo "Creating $(1)"; \
-	  $(TX) -q config mapping -r $(TXPROJ).$(1) --source-lang en --type TXT --source-file $(2) --expression "tx/$(1)-<lang>.txt" --execute; \
-	  if $(TX) -q push -r $(TXPROJ).$(1) -s >/dev/null 2>/dev/null; then \
-	    curl_output=`curl -s -L $(TXCREDS) -X PUT -d $(TXPROPS) -H "Content-Type: application/json" https://www.transifex.com/api/2/project/$(TXPROJ)/resource/$(1);` \
+	  $(TX) add --file-filter="tx-$(TXPREFIX)/$(1)-<lang>.txt" --type=TXT --organization=$(TXORG) --resource=$(1) $(2); \
+	  if $(TX) push -s $(TXPROJ).$(1) >/dev/null 2>/dev/null; then \
+	    curl_output=`$(CURL) --request PATCH \
+	                        -s -o /dev/null -w "%{http_code}" \
+	                        --url $(TXHOST)/resources/o%3A$(TXORG)%3Ap%3A$(TXPROJ)%3Ar%3A$(1) \
+	                        --header 'Accept: application/vnd.api+json' \
+	                        --header 'Authorization: Bearer $(TXCRED)' \
+	                        --header 'Content-Type: application/vnd.api+json' \
+	                        --data '{ "data": { "attributes": $(TXPROPS), \
+	                                            "id": "o:$(TXORG):p:$(TXPREFIX):r:$(1)", \
+	                                            "type": "resources" } \
+	                                }'`; \
 	    rtn=$$?; \
-	    if test $$rtn -ne 0 -o " $$curl_output" != " OK"; then echo "Warning. Failed to set properties: $$curl_output (error code $$rtn)"; fi; \
+	    if test $$rtn -ne 0 -o " $$curl_output" != " 200"; then echo "Warning. Failed to set properties: error code $$curl_output"; fi; \
 	  fi; \
 	else \
 	  echo "Updating $(1)"; \
-	  $(TX) -q push -r $(TXPROJ).$(1) -s; \
+	  $(TX) push -s $(TXPROJ).$(1); \
 	fi
 endef
 
@@ -61,13 +79,15 @@ endef
 # $(2) = lang
 
 define rsrc_pull =
-	echo "Pulling $(1)-$(2) from transifex"; \
-	$(TX) -q pull -r $(TXPROJ).$(1) -l $(2); \
-	sed -i -e '$$a\' tx/$(1)-$(2).txt; \
-	if diff -q --ignore-blank-lines tx/$(1).txt tx/$(1)-$(2).txt >/dev/null; then \
-	  echo "    no translated strings: removing"; \
-	  rm tx/$(1)-$(2).txt; \
-	fi
+	echo "Pulling $(1)-<lang> from transifex"; \
+	$(TX) pull -l $(TXLANGS) $(TXPROJ).$(1); \
+	for lang in $(LANGS); do \
+	  sed -i -e '$$a\' tx-$(TXPREFIX)/$(1)-$$lang.txt; \
+	  if diff -q --ignore-blank-lines tx-$(TXPREFIX)/$(1).txt tx-$(TXPREFIX)/$(1)-$$lang.txt >/dev/null; then \
+	    echo "    no translated strings: removing"; \
+	    rm tx-$(TXPREFIX)/$(1)-$$lang.txt; \
+	  fi; \
+	done
 endef
 
 #-- Copy src file to dest file if src and dest are different
@@ -99,15 +119,15 @@ l10n_name = $(dir $(1))$(2)/$(notdir $(1))
 
 TITLES_POTSRC = $(wildcard $(addsuffix /*.lua, $(TITLES_DIR)))
 TITLES_RSRC = $(foreach potsrc,$(TITLES_POTSRC),$(call rsrc_full_name,$(potsrc)))
-TITLES_TX = $(TITLES_RSRC:%=tx/%.txt)
+TITLES_TX = $(TITLES_RSRC:%=tx-$(TXPREFIX)/%.txt)
 TITLES_L10N = $(foreach lang,$(LANGS),$(foreach potsrc,$(TITLES_POTSRC),$(call l10n_name,$(potsrc),$(lang))))
 
 #-- Create a TX rsrc by extracting the text part of a title
 # $(1) = source file name
 
 define update-po-title =
- tx/$(call rsrc_full_name,$(1)).txt: $(1)
-	@$(mkdir_p) tx; \
+ tx-$(TXPREFIX)/$(call rsrc_full_name,$(1)).txt: $(1)
+	@$(mkdir_p) tx-$(TXPREFIX); \
 	 $(AWK) "BEGIN { isintext=0; } /^text[[:space:]]*=[[:space:]]*[\[]+/ { isintext=1; next; } /^[\]]+/ { exit; } isintext == 1 { print; }" $$< > $$@
 endef
 
@@ -121,8 +141,8 @@ $(foreach potsrc,$(TITLES_POTSRC),$(eval $(call update-po-title,$(potsrc))))
 # $(2) = lang
 
 define update-gmo-title =
- $(call l10n_name,$(1),$(2)): $(wildcard tx/$(call rsrc_full_name,$(1))-$(2).txt)
-	@if test -r tx/$(call rsrc_full_name,$(1))-$(2).txt ; then \
+ $(call l10n_name,$(1),$(2)): $(wildcard tx-$(TXPREFIX)/$(call rsrc_full_name,$(1))-$(2).txt)
+	@if test -r tx-$(TXPREFIX)/$(call rsrc_full_name,$(1))-$(2).txt ; then \
 	   $(mkdir_p) $(dir $(1))$(2); \
 	   $(AWK) "/^text[[:space:]]*=[[:space:]]*[\[]+/ { print; nextfile; } { print; } END { print \"]]\"; print \"}\"; }" \
 	        $(1) $$< > $$<.tmp; \
@@ -141,25 +161,23 @@ update-po:: $(TITLES_TX)
 #-- Push all title rsrcs to TX
 
 tx-update:: $(TITLES_TX)
-	@if [ " $(TXCREDS)" = " " ] ; then \
+	@if [ " $(TXCRED)" = " " ] ; then \
 		echo "You do not have a Transifex account"; \
 		exit 1; \
 	 fi
 	@for rsrc in $(TITLES_RSRC); do \
-		$(call rsrc_update,$$rsrc,tx/$$rsrc.txt); \
+		$(call rsrc_update,$$rsrc,tx-$(TXPREFIX)/$$rsrc.txt); \
 	 done
 
 #-- Pull all l10n versions of the titles' text from TX
 
 tx-pull:: $(TITLES_TX)
-	@if [ " $(TXCREDS)" = " " ] ; then \
+	@if [ " $(TXCRED)" = " " ] ; then \
 		echo "You do not have a Transifex account"; \
 		exit 1; \
 	 fi
-	@for lang in $(LANGS); do \
-	   for rsrc in $(TITLES_RSRC); do \
-	     $(call rsrc_pull,$$rsrc,$$lang); \
-	   done; \
+	@for rsrc in $(TITLES_RSRC); do \
+	   $(call rsrc_pull,$$rsrc); \
 	 done
 
 #-- update-gmo creates the new l10n version of the titles
@@ -170,13 +188,13 @@ update-gmo:: $(TITLES_L10N)
 
 README_DIR  = $(top_srcdir)
 README_RSRC = README
-README_TX   = tx/README.txt
+README_TX   = tx-$(TXPREFIX)/README.txt
 README_L10N = $(foreach lang,$(LANGS),$(README_RSRC:%=$(README_DIR)/README-$(lang)))
 
 #-- Copy the README into the tx/ subdir
 
-tx/README.txt: $(README_DIR)/README
-	@$(mkdir_p) tx; \
+tx-$(TXPREFIX)/README.txt: $(README_DIR)/README
+	@$(mkdir_p) tx-$(TXPREFIX); \
 	 cp $< $@
 
 
@@ -184,8 +202,8 @@ tx/README.txt: $(README_DIR)/README
 # $(1) = lang
 
 define update-gmo-readme =
- $(README_DIR)/README-$(1): $(wildcard tx/README-$(1).txt)
-	@if test -r tx/README-$(1).txt ; then \
+ $(README_DIR)/README-$(1): $(wildcard tx-$(TXPREFIX)/README-$(1).txt)
+	@if test -r tx-$(TXPREFIX)/README-$(1).txt ; then \
 	   cp $$< $$<.tmp; \
 	   $(call copy_on_diff,$$<.tmp,$$@); \
 	 fi
@@ -201,22 +219,20 @@ update-po:: $(README_TX)
 #-- Push the README rsrc to TX
 
 tx-update:: $(README_TX)
-	@if [ " $(TXCREDS)" = " " ] ; then \
+	@if [ " $(TXCRED)" = " " ] ; then \
 		echo "You do not have a Transifex account"; \
 		exit 1; \
 	 fi
-	@$(call rsrc_update,README,tx/README.txt)
+	@$(call rsrc_update,README,tx-$(TXPREFIX)/README.txt)
 
 #-- Pull all l10n versions of the README from TX
 
 tx-pull:: $(README_TX)
-	@if [ " $(TXCREDS)" = " " ] ; then \
+	@if [ " $(TXCRED)" = " " ] ; then \
 		echo "You do not have a Transifex account"; \
 		exit 1; \
 	 fi
-	@for lang in $(LANGS); do \
-	   $(call rsrc_pull,README,$$lang); \
-	 done
+	@$(call rsrc_pull,README)
 
 #-- update-gmo creates the new l10n version of the README
 
diff --git a/po/po-src/Rules-others b/po/po-src/Rules-others
--- a/po/po-src/Rules-others
+++ b/po/po-src/Rules-others
@@ -81,11 +81,20 @@ local-install:
 
 #== Transifex synchronization
 
+CURL     = curl
+TX       = tx
+TXORG    = artic-games
 TXPROJ   = freedroid-rpg
 TXPREFIX = src
-TXPROPS  = '{"category":"src"}'
-TXCRED   = $(shell $(top_srcdir)/po/tx-credentials)
+TXPROPS  = '{"category":["src"]}'
+TXCRED   = $(shell $(top_srcdir)/po/tx-credentials -t)
+TXHOST   = $(shell $(top_srcdir)/po/tx-credentials -r)
 TXRSRC   = freedroidrpg
+
+comma:= ,
+empty:=
+space:= $(empty) $(empty)
+TXLANGS = $(subst $(space),$(comma),$(foreach cata,$(CATALOGS),$(basename $(cata))))
 
 # Update the transifex potfiles
 #
@@ -106,24 +115,33 @@ tx-update: $(DOMAIN).pot
 	      echo "You do not have a Transifex account"; \
 	      exit 1; \
 	    }; \
-	$(mkdir_p) tx; \
+	$(mkdir_p) tx-$(TXPREFIX); \
 	rsrc=$(TXRSRC); \
-	cp $(DOMAIN).pot tx/$$rsrc.pot; \
-	if test -r tx/$$rsrc.pot; then \
-	  if ! tx -q status -r $(TXPROJ).$(TXPREFIX)-$$rsrc >/dev/null 2>/dev/null; then \
+	cp $(DOMAIN).pot tx-$(TXPREFIX)/$$rsrc.pot; \
+	if test -r tx-$(TXPREFIX)/$$rsrc.pot; then \
+	  if ! $(TX) status $(TXPROJ).$(TXPREFIX)-$$rsrc >/dev/null 2>/dev/null; then \
 	    echo "Creating $(TXPREFIX)-$$rsrc"; \
-	    tx -q config mapping -r $(TXPROJ).$(TXPREFIX)-$$rsrc --source-lang en --type PO --source-file tx/$$rsrc.pot --expression "tx/$$rsrc-<lang>.po" --execute; \
-	    if tx -q push -r $(TXPROJ).$(TXPREFIX)-$$rsrc -s >/dev/null 2>/dev/null; then \
-	      curl_output=`curl -s -L $(TXCRED) -X PUT -d $(TXPROPS) -H "Content-Type: application/json" https://www.transifex.com/api/2/project/$(TXPROJ)/resource/$(TXPREFIX)-$$rsrc;` \
+	    $(TX) add --file-filter="tx-$(TXPREFIX)/$$rsrc-<lang>.po" --type=PO --organization=$(TXORG) --project=$(TXPROJ) --resource=$(TXPREFIX)-$$rsrc tx-$(TXPREFIX)/$$rsrc.pot; \
+	    if $(TX) push -s $(TXPROJ).$(TXPREFIX)-$$rsrc >/dev/null 2>/dev/null; then \
+	      curl_output=`$(CURL) --request PATCH \
+	                        -s -o /dev/null -w "%{http_code}" \
+	                        --url $(TXHOST)/resources/o%3A$(TXORG)%3Ap%3A$(TXPROJ)%3Ar%3A$(TXPREFIX)-$$rsrc \
+	                        --header 'Accept: application/vnd.api+json' \
+	                        --header 'Authorization: Bearer $(TXCRED)' \
+	                        --header 'Content-Type: application/vnd.api+json' \
+	                        --data '{ "data": { "attributes": $(TXPROPS), \
+	                                            "id": "o:$(TXORG):p:$(TXPREFIX):r:$(TXPREFIX)-$$rsrc", \
+	                                            "type": "resources" } \
+	                                }'`; \
 	      rtn=$$?; \
-	      if test $$rtn -ne 0 -o " $$curl_output" != " OK"; then echo "Warning. Failed to set properties: $$curl_output (error code $$rtn)"; fi; \
+	      if test $$rtn -ne 0 -o " $$curl_output" != " 200"; then echo "Warning. Failed to set properties: error code $$curl_output"; fi; \
 	    fi; \
 	  else \
 	    echo "Updating $(TXPREFIX)-$$rsrc"; \
-	    tx -q push -r $(TXPROJ).$(TXPREFIX)-$$rsrc -s; \
+	    $(TX) push -s $(TXPROJ).$(TXPREFIX)-$$rsrc; \
 	  fi; \
 	fi; \
-	rm -rf tx
+	rm -rf tx-$(TXPREFIX)
 
 # Pull the translations from transifex.
 #
@@ -141,25 +159,25 @@ tx-pull:
 	      echo "You do not have a Transifex account"; \
 	      exit 1; \
 	    }; \
-	$(mkdir_p) tx; \
-	catalogs='$(CATALOGS)'; \
+	$(mkdir_p) tx-$(TXPREFIX); \
 	rsrc=$(TXRSRC); \
-	for cat in $$catalogs; do \
-	  cat=`basename $$cat`; \
-	  lang=`echo $$cat | sed -e 's/\.gmo$$//'`; \
-	  echo "Pulling $$rsrc-$$lang.po from transifex"; \
-	  if tx -q pull -r $(TXPROJ).$(TXPREFIX)-$$rsrc -l $$lang; then \
-	    if test -r tx/$$rsrc-$$lang.po; then \
+	echo "Pulling $$rsrc-<lang>.po from transifex"; \
+	if $(TX) pull -l $(TXLANGS) $(TXPROJ).$(TXPREFIX)-$$rsrc; then \
+	  catalogs='$(CATALOGS)'; \
+	  for cat in $$catalogs; do \
+	    cat=`basename $$cat`; \
+	    lang=`echo $$cat | sed -e 's/\.gmo$$//'`; \
+	    if test -r tx-$(TXPREFIX)/$$rsrc-$$lang.po; then \
 	      echo "Merging with $$lang.po"; \
-	      msgcat $(MSGCAT_OPTIONS) --use-first -o $$lang.po tx/$$rsrc-$$lang.po $$lang.po; \
+	      msgcat $(MSGCAT_OPTIONS) --use-first -o $$lang.po tx-$(TXPREFIX)/$$rsrc-$$lang.po $$lang.po; \
 	    else \
 	      echo "Nothing to merge"; \
 	    fi; \
-	  fi; \
-	  $(MSGMERGE_UPDATE) $(MSGMERGE_OPTIONS) $$lang.po $(DOMAIN).pot; \
-	  $(call clean_po,$$lang.po); \
-	done; \
-	rm -rf tx
+	    $(MSGMERGE_UPDATE) $(MSGMERGE_OPTIONS) $$lang.po $(DOMAIN).pot; \
+	    $(call clean_po,$$lang.po); \
+	  done; \
+	fi; \
+	rm -rf tx-$(TXPREFIX)
 
 # Push the translations to transifex.
 #
@@ -179,7 +197,7 @@ tx-push:
 	     exit 1; \
 	   }; \
 	rm -f tx-push-granted; \
-	$(mkdir_p) tx; \
+	$(mkdir_p) tx-$(TXPREFIX); \
 	catalogs='$(CATALOGS)'; \
 	rsrc=$(TXRSRC); \
 	for cat in $$catalogs; do \
@@ -187,8 +205,8 @@ tx-push:
 	  lang=`echo $$cat | sed -e 's/\.gmo$$//'`; \
 	  echo "Pushing $$rsrc-$$lang.po to transifex"; \
 	  cp $$lang.po tx/$$rsrc-$$lang.po; \
-	  tx -q push -r $(TXPROJ).$(TXPREFIX)-$$rsrc -l $$lang -t; \
+	  $(TX) push  -l $$lang -t $(TXPROJ).$(TXPREFIX)-$$rsrc; \
 	done; \
-	rm -rf tx
+	rm -rf tx-$(TXPREFIX)
 
 .PHONY: tx-update tx-pull tx-push
